# Generated by Django 5.1.7 on 2025-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
