# Generated by Django 5.1.7 on 2025-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
